#!/bin/sh
#
#  __MODULE__	napi-set-macs
#  __IDENT__	V12-000
#  __REV__	12.0
#
#  Abstract:	Remedial pass over all existing network interfaces. The primary
#		mechanism is the udev rule 75-napi-mac.rules; this script is run
#		by napi-mac.service at boot as a safety net and can be re-run
#		manually after editing /etc/napi/mac.conf.
#
#  Exit codes:	0  no errors (interfaces waiting for the EEPROM are not errors)
#		1  at least one interface reported an error
#
#  Modification history:
#	12.0	07-OCT-2026	Thin wrapper around "napi-set-mac --all", which runs
#				the pass in one process and reports interfaces
#				deferred because the EEPROM is not available yet.
#	11.0	24-SEP-2026	Version bump, no functional change.
#	10.0	24-SEP-2026	Error counting and summary; non-zero exit on failure.
#

exec /usr/lib/udev/napi-set-mac --all
